chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'

urlpatterns = [

	path('room/<int:id>/', views.course_chat_room,name='course_chat_room'),
	path('room/getapidata/', views.getapidata,name='getapidata'),


	
]

classes/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('classes/create_class/',views.create_class_view,name='create_class'),
	path('classes/class_info/<int:id>/',views.class_info_view,name='class_info'),
	path('classes/s_class_info/<int:id>/',views.s_class_info_view,name='s_class_info'),

	path('classes/s_class_info/<int:class_id>/<int:assignment_id>/details',views.s_assignment_detail_view,name='s_assignment_detail'),
	path('classes/class_info/<int:class_id>/<int:assignment_id>/update_assignment',views.update_assignment_view,name='update_assignment'),
	path('classes/class_info/<int:class_id>/<int:assignment_id>/delete_assignment',views.delete_assignment_view,name='delete_assignment'),
	
	path('classes/class_info/<int:class_id>/<int:announcement_id>/update_announcement',views.announcement_update_view,name='update_announcement'),
	path('classes/like/<int:pk>/<int:class_id>',views.announcement_likes_view,name='announcement_likes'),
	path('classes/comment/<int:announcement_id>/<int:class_id>',views.announcement_comments_view,name='announcement_comments'),
	path('classes/class_info/<int:class_id>/<int:announcement_id>/delete_announcement',views.announcement_delete_view,name='delete_announcement'),
	
	path('classes/<int:class_id>/<int:assignment_id>/student_work',views.student_work_view,name='student_work'),
	path('classes/notification/<int:notification_id>/',views.delete_notification_view,name='delete_notification'),
	# path('classes/s_class_info/<int:id>/<int:assignment_id>',views.submit_assignment_view,name='submit_assignment'),
	path('classes/class_info/<int:class_id>/attendance',views.attendance_view,name='attendance'),
	path('classes/class_info/<int:class_id>/view_attendance',views.view_attendance,name='view_attendance'),
	path('classes/class_info/<int:class_id>/<int:att_id>/edit_attendance',views.edit_attendance,name='edit_attendance'),
	path('classes/class_info/<int:class_id>/export_attendance',views.export_attendance_xls,name='export_excel'),

	path('classes/class_info/<int:class_id>/<int:quiz_id>/add_question',views.add_question_view,name='add_question'),

	path('classes/class_info/<int:class_id>/<int:s_id>/print_pdf',views.render_pdf_view,name='print_pdf'),

	path('classes/class_info/<int:class_id>/<int:s_id>/final_marks',views.add_final_marks_view,name='final_marks'),
	
	path('classes/class_info/<int:class_id>/Rate',views.rate,name='rate'),

]

studydoorwaydotcom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from .views import home,about_us_view
from chat.views import getMessages
from rest_framework import routers
from accounts.views import (
	login_view,
	register_view,
	logout_view,
	userprofile_view,
    register_as_teacher_view,
)
router=routers.DefaultRouter()
router.register(r'ajaxusers',getMessages)

app_name = 'ratings'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classes.urls')),
    path('', include('internetforum.urls')),
    path('', include('quizes.urls',namespace='quizes')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',home,name='home'),
    path('about_us/',about_us_view,name='about_us'),
    path('accounts/login/', login_view,name='login'),
    path('accounts/signup/', register_view,name='signup'),
    path('accounts/logout/', logout_view,name='logout'),
    path('accounts/userprofile/<int:profile_id>', userprofile_view,name='userprofile'),
    path('accounts/register_as_teacher/<int:prof_id>', register_as_teacher_view,name='register_as_teacher'),
    path('chat/', include('chat.urls', namespace='chat')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    
]
urlpatterns+=router.urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classes/models.py
from django.db import models
from django.contrib.auth.models import User

from .models import *



class ClassRoom(models.Model):
	SECTION = (
		('A','A'),
		('B','B'),
		('C','C'),
		('D','D'),
		)
	student_key = models.CharField(max_length=50,unique=True)
	user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	last_updated = models.DateTimeField(auto_now=True)
	class_name = models.CharField(max_length= 250)
	section = models.CharField(max_length= 200, null=True, choices=SECTION)
	subject = models.CharField(max_length= 250,null=True)
	title_image = models.ImageField(null=True,blank=True,default='classTitle image.jpg',upload_to='classTitleImages/')

	
	def __str__(self):
		return self.class_name


class Announcement(models.Model):
	user = models.ForeignKey(User,null=False,on_delete=models.CASCADE)
	announcement_text = models.TextField(max_length=500)
	announcement_file = models.FileField(blank=True,upload_to='files/announcement_file/')
	class_room = models.ForeignKey(ClassRoom,null=True, on_delete=models.CASCADE,related_name='announcements')
	announcement_date = models.DateTimeField(auto_now_add=True)
	likes = models.ManyToManyField(User, related_name = 'announcement_likes')
	last_updated = models.DateTimeField(auto_now=True)

	def total_likes(self):
		return self.likes.count()

	def __str__(self):
		return self.announcement_text

class Comment(models.Model):
	announcement = models.ForeignKey(Announcement,related_name = 'comments',on_delete=models.CASCADE)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	comment_text = models.TextField(max_length=255)
	comment_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.comment_text 

class Student(models.Model):
	class_room = models.ForeignKey(ClassRoom,null=True,on_delete=models.SET_NULL)
	student = models.ForeignKey(User,null=False,on_delete=models.CASCADE)
	added_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.student.first_name


class Instructor(models.Model):
	class_room = models.ForeignKey(ClassRoom,null=True,on_delete=models.SET_NULL)
	instructor = models.ForeignKey(User,null=False,on_delete=models.CASCADE)
	added_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.instructor.first_name


class Assignment(models.Model):
	POINTS = (
		(10,'10'),
		(20,'20'),
		(30,'30'),
		(40,'40'),
		(50,'50'),
		(60,'60'),
		(70,'70'),
		(80,'80'),
		(90,'90'),
		(100,'100'),
	)
	class_room = models.ForeignKey(ClassRoom,null=True, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	instruction = models.TextField(max_length=500,null=True,blank=True)
	file = models.FileField(blank=True,upload_to='files/t_assignments/')
	points = models.IntegerField(null=True, choices=POINTS, default=100)
	due_date = models.DateTimeField()
	assigning_date = models.DateTimeField(auto_now_add=True)
	last_updated = models.DateTimeField(auto_now=True)
	user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='assignments')

	def __str__(self):
		return self.title



class Submission(models.Model):
	file = models.FileField(upload_to='files/s_submissions/')
	submitted_at = models.DateTimeField(auto_now=True)
	last_updated = models.DateTimeField(null=True)
	assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE,related_name='submissions')
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	grade = models.IntegerField(blank=True, null=True, default=000)
	feedback = models.CharField(max_length=350, blank=True, null=True, default='No feedback yet')


class MidFinalMarks(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	class_room = models.ForeignKey(ClassRoom,null=True, on_delete=models.CASCADE)
	final_marks = models.IntegerField(blank=True, null=True, default=0,help_text='Final term obtained marks')
	final_marks_out_of = models.IntegerField(blank=True, null=True, default=0,help_text='Final term total marks')
	mid_marks = models.IntegerField(blank=True, null=True, default=0,help_text='Mid term obtained marks')
	mid_marks_out_of = models.IntegerField(blank=True, null=True, default=0,help_text='Mid term total marks')


class Notification(models.Model):
	title = models.CharField(max_length=255,null=True)
	class_room = models.ForeignKey(ClassRoom,null=True,on_delete=models.CASCADE)
	assignment = models.ForeignKey(Assignment, null=True, on_delete=models.CASCADE)
	user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='notifications')
	notification_date = models.DateField(auto_now_add=True)
	viewed = models.BooleanField(default=False)

	def get_unread_notification(self):
		return self.notification_set.filter(viewed=False)
 
class Attendance(models.Model):
	class_room = models.ForeignKey(ClassRoom, on_delete=models.DO_NOTHING)
	attendance=models.CharField(max_length=10,null=True)
	created_at = models.DateField()
	student = models.ForeignKey(Student, on_delete=models.DO_NOTHING)

class Lecture(models.Model):
	title = models.CharField(max_length=255)
	class_room = models.ForeignKey(ClassRoom,null=True,on_delete=models.CASCADE)
	files = models.FileField(blank=True,upload_to='files/lectures/')
	upload_date = models.DateTimeField(auto_now_add=True)
	last_updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title


RATE_CHOICES = [
	(1, '1 - Trash'),
	(2, '2 - Horrible'),
	(3, '3 - Terrible'),
	(4, '4 - Bad'),
	(5, '5 - OK'),
	(6, '6 - Understandable'),
	(7, '7 - Good'),
	(8, '8 - Very Good'),
	(9, '9 - Perfect'),
	(10, '10 - Master Piece'), 
]

class Review(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	class_room = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now_add=True)
	text = models.TextField(max_length=3000, blank=True)
	rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES)
	likes = models.PositiveIntegerField(default=0)
	unlikes = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.user.username

classes/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from quizes.models import Quiz
from questions.models import Question,Answer
from django.contrib import admin


class RateForm(forms.ModelForm):
	text = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=False)
	rate = forms.ChoiceField(choices=RATE_CHOICES, widget=forms.Select(), required=True)

	class Meta:
		model = Review
		fields = ('text', 'rate')

class DateInput(forms.DateInput):
	input_type = 'date'


class CreateClassRoom(ModelForm):
	student_key = forms.CharField(max_length=50,help_text='Enter the class joining key so students can use this key to enroll in this classroom')
	class Meta:
		model = ClassRoom
		fields = '__all__'
		exclude = ['user',]

	def clean_student_key(self):
		student_key = self.cleaned_data['student_key']
		if ClassRoom.objects.filter(student_key=student_key).exists():
			raise forms.ValidationError('Class room with this Student key already exists')
		return student_key

class EditClassRoom(ModelForm):
	class Meta:
		model = ClassRoom
		fields = '__all__'
		exclude = ['user',]
		

class CreateAssignment(ModelForm):
	class Meta:
		model = Assignment
		widgets = {'due_date' : DateInput()}
		fields = '__all__'
		exclude = ['user','class_room']

# class UploadLecture(ModelForm):
# 	class Meta:
# 		model = Lecture
# 		fields = '__all__'
# 		exclude = ['class_room']


class JoinClassRoom(forms.Form):
	student_key = forms.CharField(max_length=50,help_text='Enter the class joining key provided by class creator')


	def clean_student_key(self):
		student_key = self.cleaned_data['student_key']
		if not ClassRoom.objects.filter(student_key=student_key).exists():
			raise forms.ValidationError('No classroom exists with provided key')
		return student_key

class CreateAnnouncement(ModelForm):
	class Meta:
		model = Announcement
		fields = '__all__'
		exclude = ['user','class_room','likes']

# Quizes Forms 
class CreateQuiz(ModelForm):
	class Meta:
		model = Quiz
		fields = '__all__'
		exclude = ['created_by','class_room']

class QuizQuestionForm(ModelForm):
	text = forms.CharField(max_length=250,help_text='Enter question text here.')

	class Meta:
		model = Question
		fields = '__all__'

class QuizAnswerForm(ModelForm):
	text = forms.CharField(max_length=250,help_text='Enter answer text here.')
	class Meta:
		model = Answer
		fields = '__all__'
		exclude = ['question']


		
class SubmitAssignment(ModelForm):
	class Meta:
		model = Submission
		fields = ['file']

class GradeForm(forms.Form):
    grade = forms.IntegerField(help_text='Enter points obtained')

    class Meta:
        fields = ['grade']

class FeedbackForm(forms.Form):
    feedback = forms.CharField(help_text='Enter your feedback')
    
    class Meta:
        fields = ['feedback']

class AttendanceForm(ModelForm):
	created_at = models.DateField(help_text='Select date for attendance')
	class Meta:
		model = Attendance
		widgets = {'created_at' : DateInput()}
		fields = ['created_at']

	def clean_created_at(self):
		created_at = self.cleaned_data['created_at']
		if Attendance.objects.filter(created_at=created_at).exists():
			raise forms.ValidationError('You have already submitted attendance for this date')
		return created_at 

class EditAttendanceForm(ModelForm):
	class Meta:
		model = Attendance
		fields = ['attendance']


class MidFinalMarksForm(ModelForm):
	class Meta:
		model = MidFinalMarks
		fields = '__all__'
		exclude =['student','class_room']

templates/classes/add_question.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}


<link rel="stylesheet" type="text/css" href="{% static '/css/class_info.css' %}">

{% include 'side_panel.html' %}
<div class="container" style="margin-top:85px">
	<form method="POST">
		{% csrf_token %}
		<div class="row">
			<div class="col-md-4">
				<h4 class="card-title">Question</h4>
				{{question_form|crispy}}
			</div>
			<div class="col-md-8">
				<h4 class="card-title">Answer Choices</h4>
				{{formset|crispy}}
			</div>
		</div>
		<button class="btn btn-dark">Add</button>
			
	</form>
</div>

{% endblock %}

templates/classes/attendance.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}






<link rel="stylesheet" type="text/css" href="{% static '/css/class_info.css' %}">
<script>
    document.formHasErrors = {% if attendanceForm.errors %}true{% else %}false{% endif %};
</script>
{% include 'side_panel.html' %}
<div class="container" style="margin-top:90px">
	
	
	<div class="card">
		<div class="card-header">
			<h5 class="card-title">Student attendance <span class="badge badge-pill badge-primary">{{class_room.class_name}}</span>
				<button type="submit" id="submit-attendance" class="btn btn-danger m-2 float-right">Submit Attendance</button> 
			 </h5>
			<div class="card-tools">
        <div class="input-group input-group-sm" style="width: 250px;">
        	{% for msg in messages %}
      		<p class="text-success">{{msg}}</p>
      		{% endfor %}
        	<form method="POST" id="myform">
        		<label >Select Date for attendance</label>
        		{% csrf_token %}
        		{{attendanceForm|crispy}}
        		<button type="submit" id="submit-date" name="submit-date" class="btn btn-success">Select</button>
        	</form>
          <!-- <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

          <div class="input-group-append">
            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
          </div> -->
        </div>
      </div>
      <div id="att-date" class="pt-3">
			</div>
			<a class="text-center" href="{% url 'view_attendance' class_room.id %}">View Attendance</a>
		</div>
		<div class="card-body table-responsive p-0">
			<table class="table table-sm table-hover text-nowrap ">
				<thead class="thead-light">
					<tr>
						<th>Student Name</th>
						<th>Date Joined</th>
						<th>Email</th>
						<th>Attendance</th>
					</tr>
				</thead>
				<tbody>
					{% csrf_token %}
					{% for student in students %}
					<tr>
						<td>{{student.student.first_name}} {{student.student.last_name}}</td>
						<td>{{student.added_at}}</td>
						<td>{{student.student.email}}</td>
						<td>
							<input type="checkbox" name="student_id[]" id="present" value="{{student.id}}" required><b>P</b>
							<input type="checkbox" name="student_id[]" id="absent" value="{{student.id}}"><b>A</b>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>	
</div>






<script type="text/javascript">
	console.log('attendance.js')
	$(document).ready(function(){
		var attDate = $('input[name="created_at"]').val();
		const att_date = document.getElementById('att-date');
		if (attDate === ""){
			document.getElementById('submit-attendance').disabled=true;
		}
		else{
			att_date.innerHTML += `<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
										<p>You are going to submit attendance for the date <b style="color:black">${attDate}</b></p>
										<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										    <span aria-hidden="true">&times;</span>
										</button>
									</div>
									`
		}
		var formError = {% if attendanceForm.errors %}true{% else %}false{% endif %};
		if (formError){
			document.getElementById('submit-attendance').disabled=true$("#myform")[0].reset();		}
		var attendance = []
		const attendanceBox = document.getElementById('attendance-box')
		$('#submit-attendance').click(function(){
			var attDate = $('input[name="created_at"]').val();
			var p_ids = [];
			var a_ids = [];
			var csrf = $('input[name=csrfmiddlewaretoken').val();
			$('#present:checked').each(function(i){
				p_ids[i]=$(this).val();
				console.log('p_ids'+ p_ids);
			})
			$('#absent:checked').each(function(i){
				a_ids[i]=$(this).val();
				console.log('a_ids'+ a_ids);
			})
			
			
				$.ajax({
				url:window.location.href,
				method:'POST',
				data:{
					attDate,
					p_ids,
					a_ids,
					csrfmiddlewaretoken:csrf,
				},
				success:function(response){
					$("#myform")[0].reset();
					attendance = response.attendance
					console.log(attendance)
					location.reload()
				},
			})	
			
			
		})
		$("#myform")[0].reset();
	})
</script>


{% endblock content %}

templates/classes/delete_announcement.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}


<link rel="stylesheet" type="text/css" href="{% static '/css/class_info.css' %}">

{% include 'side_panel.html' %}
<div class="container" style="margin-top:80px">
	<div class="card border-primary mb-2">
		<div class="card-body">
			<h5 class="card-title">Announcement {{announcement.id}}</h5>
			<div class="card-text text-muted"><small>Last updated {{announcement.last_updated|naturaltime}}</small></div>
			<div class="card border-info text-center m-4">
				<h5 class="card-title m-4">Are you sure you want to delete this Announcement ?</h5>
				<div class="card-text text-muted m-2">{{announcement.announcement_text}}</div>
				<form method="POST">
					{% csrf_token %}
					<button type="submit" class="btn btn-outline-danger m-4" name="delete_announcement">Delete</button>
				</form>
			</div>
		</div>	
	</div>
</div>

{% endblock %}

templates/classes/edit_attendance.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container" style="margin-top:85px">
	<div class="card">
		<div class="card-header">
			<h5 class="card-title">Edit attendance <span class="badge badge-pill badge-primary">{{class_room.class_name}}</span></h5>
		</div>
		<div class="card-body p-2 text-center">
			<h5>Student Name : {{attendance.student.student.first_name}} {{attendance.student.student.last_name}}</h5>
			<h5>Attendance Date : {{attendance.created_at}}</h5>
			<form method="POST">
				{% csrf_token %}
				{{edit_att_form|crispy}}
				<button type="submit" class="btn btn-outline-dark">Submit</button>
			</form>
		</div>
	</div>
</div> 
 


{% endblock content %}

templates/classes/example.html
{% for std in students %}
<h3>{{std.student.first_name}}</h3>
{% for sa in std.attendance_set.all %}
<h5> {{sa.created_at}} -- {{sa.present}}</h5>
{% endfor %}
{% endfor %}

<table>

	<tr>
		<th>Student Name</th>
		{% for at in att %}
		<th>{{at}}</th>
		{% endfor %}
	</tr>
	{% for std in students %}
	<tr>
		<td>{{std.student.first_name}}</td>
		{% for sa in std.attendance_set.all %}
		<td>{{sa.attendance}}</td>
		{% endfor %}
	</tr>
	{% endfor %}
</table>

templates/classes/final_marks.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static '/css/class_info.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/css/student_work.css' %}">	
{% include 'side_panel.html' %}
<div class="container" style="margin-top:80px">
	<div class="row">
		<div class="col">
  			<div class="card-counter success">
        		<i class="fa fa-address-card"></i>
        		<span class="count-numbers">{{student.student.first_name}} {{student.student.last_name}}</span>
        		<span class="count-name">{{student.class_room}}</span>
      		</div>
  		</div>
  	</div>
  	<hr style="border-top: 1px solid tomato;margin-top:10px;">
	<div class="card border-success">
		<div class="card-header text-center">
			<h4>Mid term & Final term marks</h4>
		</div> 
		<div class="card-body">
			<form method="POST">
				{% csrf_token %}
				<div class="row">
					<div class="col">
						{{form.mid_marks|as_crispy_field}}
					</div>
					<div class="col">
						{{form.mid_marks_out_of|as_crispy_field}}
					</div>
				</div>
				<div class="row">
					<div class="col">
						{{form.final_marks|as_crispy_field}}
					</div>
					<div class="col">
						{{form.final_marks_out_of|as_crispy_field}}
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
</div>


{% endblock content %}

templates/classes/s_assignment_detail.html
{% extends 'main.html' %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load filename %}


{% block content %}
<style>
	#card-sub{
		box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  		transition: 0.4s;
	}
	#card:hover {
	  	box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
	}
	#card-sub span:hover {
		color:green;
	}
</style>

<div class="container" style="margin-top:80px">
	<div class="row">
		<div class="col-sm-8 m-2">
			<span class="float-left" style="color:tomato"><i class="fas fa-file-alt fa-3x"></i></span>
			
			<div class="ml-5">
				<h3>{{assignment.title}}</h3>
				<p class="text-muted" style="font-size:small;">{{assignment.user.username}} . {{assignment.assigning_date}}</p>
				<p><b>Points : {{assignment.points}}<span class="float-right">Due {{assignment.due_date}}</span></b></p>
				
			</div>
			<hr class="ml-4" style="border-top: 1px solid #F06529;">
			<div class="container ml-4">
				<p>
					{{assignment.instruction}}
				</p>
				{% if assignment.file %}
				<div class="card p-3 m-3 text-center" id="card-sub"style="background-color: #ebdecc">
					<i class="fas fa-file-alt"></i><a href="{{ assignment.file.url }}">Download File</a>
					{{assignment.file|getfilename}}
				</div>
				{% else %}
				<div class="card rounded p-3 m-3 text-muted text-center">
					<i class="fas fa-file-alt"></i>No file included 
				</div>
				{% endif %}
			</div>
		</div>
		<div class="col-sm-3 m-2">
			<div class="card rounded">
				<div class="card-body">
					<h5 class="card-title text-muted">Your Work
						{% if s_submission.grade != 'No grade yet' %}<span class="float-right">{{s_submission.grade}}/{{assignment.points}}</span>
						{% else %}<span class="float-right">-/{{assignment.points}}</span>{% endif %}
					</h5>
					{% if s_submission %}
					<div class="card rounded p-1 m-1 text-center">
						
						<span style="color:tomato"><i class="fas fa-file-alt fa-2x"></i></span>
						<a href="{{ s_submission.file.url }}"><small>{{s_submission.file|getfilename}}</small></a>
						
					</div>
					<p class="text-secondary text-center" style="font-size:small;">Submitted at . {{s_submission.submitted_at|date:"d M, Y"}}</p>
						{% if s_submission.last_updated %}
						<p class="text-muted" style="font-size:small;">Last updated . {{s_submission.last_updated|naturaltime}}</p>
						{% endif %}
					<div class="card rounded p-1">
						<button class="btn btn-outline-primary btn-block" type="button" id="dropDownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus"></i>Add or create</button>
						<div class="dropdown-menu" aria-labelledby="dropDownMenuButton">
						    <a class="dropdown-item" ><i class="far fa-file-alt"></i>
						    	File
						    	<form method="POST",action="", enctype="multipart/form-data">
						    		{% csrf_token %}
						      		{{submission_form|crispy}}
							</a>
						</div>
						<div class="text-center m-2 p-2">
				      		<button type="submit" class="btn btn-primary btn-block" name="resubmit_assignment">
				      			Resubmit
				      		</button>
				      		</form>
					    </div>
					</div>
					{% else %}
					<div class="card rounded p-1">
						<button class="btn btn-outline-primary btn-block" type="button" id="dropDownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-plus"></i>Add or create</button>
						<div class="dropdown-menu" aria-labelledby="dropDownMenuButton">
						    <a class="dropdown-item" ><i class="far fa-file-alt"></i>
						    	File
						    	<form method="POST",action="", enctype="multipart/form-data">
						    		{% csrf_token %}
						      		{{submission_form|crispy}}
							</a>
						</div>
						<div class="text-center m-2 p-2">
				      		<button type="submit" class="btn btn-primary btn-block" name="submit_assignment">
				      			Submit
				      		</button>
				      		</form>
					    </div>
					</div>
					{% endif %}
				</div>
			</div>
			<div class="card rounded m-1">
				<div class="card-body">
					<h6 class="card-title">Feedback</h6>
					{% if s_submission.feedback != 'No feedback yet'%}
					<div class="card-text text-secondary">	
						<small>{{s_submission.feedback}}</small>
					</div>
					{% else %}
					<h6 class="card=title text-center text-muted"><small>No feedback yet.</small></h6>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}