chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'

urlpatterns = [

	path('room/<int:id>/', views.course_chat_room,name='course_chat_room'),
	path('room/getapidata/', views.getapidata,name='getapidata'),


	
]

internetforum/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('internetforum/forum_home/',views.forum_homepage,name='forum_home'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('save-upvote',views.save_upvote,name='save-upvote'),
    path('save-downvote',views.save_downvote,name='save-downvote'),
    # # User Register
    # path('accounts/register/',views.register,name='register'),
    # Profile
    path('user-dashboard',views.user_dashboard,name='user-dashboard'),
    # Ask Question
    path('ask-question',views.ask_form,name='ask-question'),
    # Tag Page
    path('tag/<str:tag>',views.tag,name='tag'),
    # Tags Page
    path('tags',views.tags,name='tags'),
]

studydoorwaydotcom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from .views import home,about_us_view
from chat.views import getMessages
from rest_framework import routers
from accounts.views import (
	login_view,
	register_view,
	logout_view,
	userprofile_view,
    register_as_teacher_view,
)
router=routers.DefaultRouter()
router.register(r'ajaxusers',getMessages)

app_name = 'ratings'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classes.urls')),
    path('', include('internetforum.urls')),
    path('', include('quizes.urls',namespace='quizes')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',home,name='home'),
    path('about_us/',about_us_view,name='about_us'),
    path('accounts/login/', login_view,name='login'),
    path('accounts/signup/', register_view,name='signup'),
    path('accounts/logout/', logout_view,name='logout'),
    path('accounts/userprofile/<int:profile_id>', userprofile_view,name='userprofile'),
    path('accounts/register_as_teacher/<int:prof_id>', register_as_teacher_view,name='register_as_teacher'),
    path('chat/', include('chat.urls', namespace='chat')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    
]
urlpatterns+=router.urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internetforum/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from ckeditor.fields import RichTextField 

# Custom User Model
# class CustomUser(AbstractUser):
#     bio=models.TextField()
#     location=models.CharField(max_length=200)


# Question Model
class Question(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    detail=RichTextField()
    tags=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# Answer Model
class Answer(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    detail=RichTextField()
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.detail

# Comment
class Comment(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='comment_user')
    comment=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

# UpVotes
class UpVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='upvote_user')

# DownVotes
class DownVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='downvote_user')

internetforum/forms.py
from django.forms import ModelForm
from django import forms
from .models import Answer,Question


class AnswerForm(ModelForm):
	class Meta:
		model = Answer
		fields = ('detail',)

class QuestionForm(ModelForm):

	class Meta:
		widgets = {
		'tags':forms.Textarea(attrs={'rows':3}),
		}
		model = Question
		fields = ('title','detail','tags')

internetforum/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from .models import Question,Answer,Comment,UpVote,DownVote
from django.http import JsonResponse
from .forms import AnswerForm,QuestionForm
from django.contrib import messages
from django.db.models import Count

# Internet Forum Homepage
def forum_homepage(request):
    
	if 'q' in request.GET:
		q=request.GET['q']
		quests = Question.objects.annotate(total_comments=Count('answer__comment')).filter(title__icontains=q).order_by('-id')
	else:
		quests = Question.objects.annotate(total_comments=Count('answer__comment')).all().order_by('-id')
	paginator = Paginator(quests,4)
	page_num = request.GET.get('page',1)
	quests = paginator.page(page_num)

	return render(request,'internetforum/forum_home.html',{'quests':quests,'tags':tags})


# Detail
def detail(request,id):
	quest = Question.objects.get(pk=id)
	tags = quest.tags.split(',')
	answers = Answer.objects.filter(question=quest)
	answerform = AnswerForm
	if request.method =='POST':
		answerData = AnswerForm(request.POST)
		if answerData.is_valid():
			answer = answerData.save(commit=False)
			answer.question = quest
			answer.user = request.user
			answer.save()
			messages.success(request,'Answer has been submitted')
			return redirect('detail',id=id)
	context = {
		'quest':quest,
		'tags':tags,
		'answers':answers,
		'answerform':answerform		
	}
	return render(request,'internetforum/detail.html',context)


# Save Comment
def save_comment(request):
    if request.method=='POST':
        comment=request.POST['comment']
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        Comment.objects.create(
            answer=answer,
            comment=comment,
            user=user
        )
        return JsonResponse({'bool':True})


# Save Upvote
def save_upvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=UpVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            UpVote.objects.create(
                answer=answer,
                user=user,
            )
            return JsonResponse({'bool':True})

# Save Downvote
def save_downvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=DownVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            DownVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})


# Ask Form
def ask_form(request):
    form=QuestionForm
    if request.method=='POST':
        questForm=QuestionForm(request.POST)
        if questForm.is_valid():
            questForm=questForm.save(commit=False)
            questForm.user=request.user
            questForm.save()
            messages.success(request,'Question has been added.')
            return redirect('ask-question')
    return render(request,'internetforum/ask-question.html',{'form':form})


# Questions according to tag
def tag(request,tag):
    quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(tags__icontains=tag).order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'internetforum/tag.html',{'quests':quests,'tag':tag})


# Tags Page
def tags(request):
    if 't' in request.GET:
        t=request.GET['t']
        quests = Question.objects.filter(title__icontains=t).order_by('-id')
        if not quests:
            messages.warning(request,'Tag not found!')
    else:
        quests=Question.objects.all()
    paginator = Paginator(quests,10)
    page_num = request.GET.get('page',1)
    quests = paginator.page(page_num)

    # quests=Question.objects.all()
    tags=[]
    for quest in quests:
        qtags=[tag.strip() for tag in quest.tags.split(',')]
        for tag in qtags:
            if tag not in tags:
                tags.append(tag)
    # Fetch Questions
    tag_with_count=[]
    for tag in tags:
        tag_data={
            'name':tag,
            'count':Question.objects.filter(tags__icontains=tag).count()
        }
        tag_with_count.append(tag_data)
    return render(request,'internetforum/tags.html',{'tags':tag_with_count,'quests':quests})

# Profile
def user_dashboard(request):
    quests=Question.objects.filter(user=request.user).order_by('-id')
    answers=Answer.objects.filter(user=request.user).order_by('-id')
    comments=Comment.objects.filter(user=request.user).order_by('-id')
    upvotes=UpVote.objects.filter(user=request.user).order_by('-id')
    downvotes=DownVote.objects.filter(user=request.user).order_by('-id')
    
    label = ['Questions', 'Upvotes', 'Downvotes','Answers','Comments']
    data = [quests.count(), upvotes.count(), downvotes.count(),answers.count(), comments.count()]
    return render(request,'internetforum/user-dashboard.html',{
        'quests':quests,
        'answers':answers,
        'comments':comments,
        'upvotes':upvotes,
        'downvotes':downvotes,
        'label':label,
        'data':data,
    })

templates/internetforum/detail.html
{% extends 'main.html'%}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'internet_forum_nav.html'%}


<!-- Question List -->  

<div class="container">
  <h2 class="mt-5">{{quest.title}}</h2>
  <p style="font-size:small;">
    <span class="mr-4 text-muted">Asked {{quest.add_time|naturaltime}}</span>
    <a href="#">{{quest.user.username}}</a>
    <span class="ml-4 text-muted">{{quest.answer_set.count}} Answer{{quest.answer_set.count|pluralize}}</span>
  </p>
  <p> {{quest.detail|safe}} </p>
  <p>
    tags:
      {% for tag in tags %}
      <a href="/tag/{{tag|slugify}}" class="badge badge-secondary p-1">{{tag}}</a>
      {% endfor %}
  </p>
  <a href="#post-answer">Post answer to this question</a>
   
  <hr style="border-top: 1px solid #F06529;">



  {% for answer in answers %}  
  <div class="row">
    <div class="col-1">
      <div class="upvote">
        <strong class="upvote-count-{{answer.id}}">{{answer.upvote_set.count}}</strong><br/>
        <span class="text-success">
          <i class="fa fa-arrow-up fa-2x upvote-click" data-answer="{{answer.id}}"></i>
        </span>
      </div>
      <div class="downvote mt-3">
        <span class="text-danger">
          <i class="fa fa-arrow-down fa-2x downvote-click" data-answer="{{answer.id}}"></i>
        </span><br/>
        <strong class="downvote-count-{{answer.id}}">{{answer.downvote_set.count}}</strong>
      </div>
    </div>
    <div class="col-11">
      <p>
        {{answer.detail|safe}}
      </p>
      <p style="font-size:small;">
        <span class="mr-3 text-muted">Answered {{answer.add_time|naturaltime}}</span>
        <a href="#" class="mr-3">{{answer.user.username}}</a>
        <span class="mr-3"><span class="comment-count-{{answer.id}}">{{answer.comment_set.count}}</span> Comment{{answer.comment_set.count|pluralize}}</span>
      </p>

    <!--   Comment Section Starts  -->
      <h3 class="my-4">Comments</h3>
      <hr style="border-top: 1px solid #F06529;">
      <div class="comment-wrapper-{{answer.id}}">
        {% for comment in answer.comment_set.all %}
        <div class="card mb-2">
          <div class="card-body round" style="background-color: #fafaf7">
            <p>{{comment.comment}} </p>
            <p class="text-muted" style="font-size:small;font-style:italic;">
              <span class="mr-3 text-muted">Commented {{comment.add_time|naturaltime}}</span>
              <a href="">{{comment.user.username}}</a>
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- Comment Form -->
      <div class="card my-3">
        <h6 class="card-header">Add Comment</h6>
        <div class="card-body">
          <textarea class="form-control comment-text-{{answer.id}}"></textarea>
          <button type="button" data-answer="{{answer.id}}" class="btn btn-dark my-3 save-comment">Submit</button>
        </div>
      </div>
    </div>
  </div>
  <hr style="border-top: 1px solid #F06529;">
  {% endfor %}
    <form method="post">
      {% csrf_token %}
      {{answerform.media}}
      <div class="card bg-light mb-3" id="post-answer">
        <div class="card-header">Your Answer</div>
        <div class="card-body">
            {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
            {% endfor %}
          {{answerform}}
        </div>
        <div class="card-footer text-center">
           <button type="submit" class="btn btn-dark btn-lg ">Post Your Answer<i class="fa fa-paper-plane"></i>
           </button>
        </div>
      </div>
    </form>
</div>

<script>
  $(document).ready(function() {
    $(".save-comment").on('click',function() {
      var _answerid=$(this).data('answer');
      var _comment=$(".comment-text-"+_answerid).val();
      console.log(_comment,_answerid);
      //Ajax
      $.ajax({
        url:"/save-comment",
        type:"post",
        data:{
          comment:_comment,
          answerid:_answerid,
          csrfmiddlewaretoken:"{{csrf_token}}"
        },
        dataType:'json',
        beforeSend:function(){
           $(".save-comment").addClass('disabled').text('saving...');
        },
        success:function(res){
          console.log(res);
          if(res.bool==true){
            $(".comment-text-"+_answerid).val('');
            //Apend Element
            var _html='<div class="card mb-2 animate__animated animate__pulse">\
          <div class="card-body">\
            <p>'+_comment+' </p>\
            <p>\
              <a href="">{{request.user}}</a>\
            </p>\
          </div>\
        </div>';
        $(".comment-wrapper-"+_answerid).append(_html);
        var prevCount = $(".comment-count-"+_answerid).text();
        $(".comment-count-"+_answerid).text(parseInt(prevCount)+1);
          }
          $(".save-comment").removeClass('disabled').text('Submit');
        }
      });
    });

    //UpVote click

     $(".upvote-click").on('click',function(){
        var answerid=$(this).data('answer');
        // Ajax
        $.ajax({
            url:"/save-upvote",
            type:"post",
            data:{
                answerid:answerid,
                csrfmiddlewaretoken:"{{csrf_token}}"
            },
            dataType:'json',
            success:function(res){
                console.log(res);
                var _prevupvote=$(".upvote-count-"+answerid).text();
                if(res.bool==true){
                    $(".upvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                }
            }
        });
      });

     // Downvote
      $(".downvote-click").on('click',function(){
          var answerid=$(this).data('answer');
          // Ajax
          $.ajax({
              url:"/save-downvote",
              type:"post",
              data:{
                  answerid:answerid,
                  csrfmiddlewaretoken:"{{csrf_token}}"
              },
              dataType:'json',
              success:function(res){
                  var _prevupvote=$(".downvote-count-"+answerid).text();
                  if(res.bool==true){
                      $(".downvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                  }
              }
          });
      });
  });
</script>

{% endblock %}

templates/internetforum/forum_home.html
{% extends 'main.html'%}
{% load static %}

{% block content %}

{% include 'internet_forum_nav.html' %}
<style>
   #popup {
    display:none;
    position:fixed;
    margin:0 auto;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 9999;
  }
  #close{
    position:absolute;
    top:0; 
    right:0;
    margin:10px;
  }
 
</style>

<!-- popup image  -->
<div id="popup">
    <img src="{% static 'images/ask_question.png' %}" alt="popup">
    <i id="close" class="fa fa-window-close fa-2x" aria-hidden="true" style="color:white"></i>
</div>

<!-- Search Section -->
<div class="container py-5">
    <div class="row">
        <div class="col-md-8 offset-2">
            <form>
                <div class="input-group">
                    <input type="text" name="q" class="form-control form-control-lg" placeholder="Search" />
                    <div class="input-group-append">
                    <button class="btn btn-dark btn-lg" type="submit" id="button-addon2">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Question List -->  

<div class="container">
    {% for quest in quests %}
    <div class="card mb-4 shadow">
        <div class="card-body">
            <h4 class="card-title"><a href="/detail/{{quest.id}}">{{quest.title}}</a></h4>
            <p class="card-text">{{quest.detail|safe}}</p>
            <p>
              <p class="text-muted" style="font-size:small;font-style:italic;">by__
                <a href="">{{quest.user.username}}</a>
              </p>
                <!-- <a href="#" class="mr-2" >{{quest.user.username}}</a> -->
                <a href="/detail/{{quest.id}}" class="mr-2">{{quest.answer_set.count}} Answers</a>
                <a href="/detail/{{quest.id}}" class="mr-2">{{quest.total_comments}} Comments</a>
            </p>
        </div>
        <div class="card-footer" style="background: linear-gradient(to right, #ffccff 0%, #ffffff 100%);">
            <small>{{quest.add_time}}</small>
        </div>
    </div>
    {% endfor %}
</div>
{% if quests.has_other_pages %}
<!-- Pagination -->
<nav class="my-3 container">
    <ul class="pagination">
        {% if quests.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
      {% endif %}
      {% for i in quests.paginator.page_range %}
      {% if quests.number == i %}
      <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      {% if quests.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
      {% endif %}
    </ul>
</nav>
{% endif %}


<!-- popup image script  -->
<script>

  //with this first line we're saying: "when the page loads (document is ready) run the following script"
  $(document).ready(function () {

      //select the POPUP FRAME and show it
      $("#popup").hide().fadeIn(2000);

      //close the POPUP if the button with id="close" is clicked
      $("#close").on("click", function (e) {
          e.preventDefault();
          $("#popup").fadeOut(1000);
      });

  });
</script>
{% endblock %}

templates/internetforum/tag.html
{% extends 'main.html' %}
{% load humanize %}
{% block title %}{{tag}}{% endblock %}
{% block content %}

{% include 'internet_forum_nav.html' %}
    <!-- Question List -->
    <div class="container py-5">
        {% for quest in quests %}
        <div class="card mb-3">
            <div class="card-body">
                <h4 class="card-title"><a href="/detail/{{quest.id}}">{{quest.title}}</a></h4>
                <p class="card-text">{{quest.detail}}</p>
                <p>
                    <a href="#" class="mr-2">{{quest.user.username}}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}

templates/internetforum/user-dashboard.html
{% extends 'main.html'%}
{% load humanize %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'internet_forum_nav.html'%}

<div class="container py-5">
    <div class="row">
        <div class="col-md-3">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                
                <a class="nav-link active" id="v-pills-questions-tab" data-toggle="pill" href="#v-pills-questions" role="tab" aria-controls="v-pills-questions" aria-selected="true">Questions</a>
                <a class="nav-link" id="v-pills-answers-tab" data-toggle="pill" href="#v-pills-answers" role="tab" aria-controls="v-pills-answers" aria-selected="false">Answers</a>
                <a class="nav-link" id="v-pills-comments-tab" data-toggle="pill" href="#v-pills-comments" role="tab" aria-controls="v-pills-comments" aria-selected="false">Comments</a>
                <a class="nav-link" id="v-pills-upvotes-tab" data-toggle="pill" href="#v-pills-upvotes" role="tab" aria-controls="v-pills-upvotes" aria-selected="false">UpVotes</a>
                <a class="nav-link" id="v-pills-downvotes-tab" data-toggle="pill" href="#v-pills-downvotes" role="tab" aria-controls="v-pills-downvotes" aria-selected="false">DownVotes</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                    <canvas id="myChart" width="450" height="100"></canvas>
            </div>
            <div class="tab-content" id="v-pills-tabContent">
                <!-- Questions -->
                <div class="tab-pane fade show active" id="v-pills-questions" role="tabpanel" aria-labelledby="v-pills-questions-tab">
                    <div class="card">
                        <h5 class="card-header text-white" style="background: linear-gradient(to right, #009999 0%, #9999ff 100%);">My Questions <span class="badge badge-primary">{{quests.count}}</span></h5>
                        <div class="card-body">
                            {% for quest in quests %}
                            <p><a href="/detail/{{quest.id}}">{{quest.title}}</a></p>
                            <hr />
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!-- Answers -->
                <div class="tab-pane fade" id="v-pills-answers" role="tabpanel" aria-labelledby="v-pills-answers-tab">
                    <div class="card">
                        <h5 class="card-header text-white" style="background: linear-gradient(to right, #009999 0%, #9999ff 100%);">My Answers <span class="badge badge-primary">{{answers.count}}</span></h5>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Question</th>
                                    <th>Answer</th>
                                </tr>
                                {% for ans in answers %}
                                <tr>
                                    <td><a href="/detail/{{ans.question.id}}">{{ans.question.title}}</a></td>
                                    <td><a href="/detail/{{ans.question.id}}">{{ans.detail|safe}}</a>
                                    	<span class="mr-3"><span class="comment-count-{{answer.id}}">{{ans.comment_set.count}}</span> Comment{{ans.comment_set.count|pluralize}}</span>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="v-pills-comments" role="tabpanel" aria-labelledby="v-pills-comments-tab">
                    <div class="card">
                        <h5 class="card-header text-white" style="background: linear-gradient(to right, #009999 0%, #9999ff 100%);">My Comments <span class="badge badge-info">{{comments.count}}</span></h5>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <tr>
                                    <th>Question</th>
                                    <th>Answer</th>
                                    <th>Comment</th>
                                </tr>
                                {% for comment in comments %}
                                <tr>
                                    <td><a href="/detail/{{comment.answer.question.id}}">{{comment.answer.question.title}}</a></td>
                                    <td><a href="/detail/{{comment.answer.questionans.question.id}}">{{comment.answer.detail|safe}}</a></td>
                                    <td><a href="/detail/{{comment.answer.question.id}}">{{comment.comment}}</a></td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="v-pills-upvotes" role="tabpanel" aria-labelledby="v-pills-upvotes-tab">
                    <div class="card">
                        <h5 class="card-header text-white" style="background: linear-gradient(to right, #009999 0%, #9999ff 100%);">My Upvotes <span class="badge badge-info">{{upvotes.count}}</span></h5>
                        <div class="card-body">
                    <table class="table table-bordered">
                        <tr>
                            <th>Question</th>
                            <th>Answer</th>
                        </tr>
                        {% for upvote in upvotes %}
                        <tr>
                            <td><a href="/detail/{{upvote.answer.question.id}}">{{upvote.answer.question.title}}</a></td>
                            <td><a href="/detail/{{upvote.answer.question.id}}">{{upvote.answer.detail|safe}}</a></td>
                        </tr>
                        {% endfor %}
                    </table>
                    </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="v-pills-downvotes" role="tabpanel" aria-labelledby="v-pills-downvotes-tab">
                    <div class="card">
                        <h5 class="card-header text-white" style="background: linear-gradient(to right, #009999 0%, #9999ff 100%);">My Downvotes <span class="badge badge-info">{{downvotes.count}}</span></h5>
                        <div class="card-body">
                    <table class="table table-bordered">
                        <tr>
                            <th>Question</th>
                            <th>Answer</th>
                        </tr>
                        {% for downvote in downvotes %}
                        <tr>
                            <td><a href="/detail/{{downvote.answer.question.id}}">{{downvote.answer.question.title}}</a></td>
                            <td><a href="/detail/{{downvote.answer.question.id}}">{{downvote.answer.detail|safe}}</a></td>
                        </tr>
                        {% endfor %}
                    </table>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for l in label %}'{{l}}',{% endfor %}],
        datasets: [{
            label: ['Total'],
            data: [{% for d in data %}{{d}},{% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endblock %}